### ISSUE TITLE
Support default values in schema according to GraphQL spec

### ISSUE THREAD

**Issue by kibagateaux** [graphprotocol/support#63]
Hey Graph team. Just want to say this is my first time using The Graph and it's awesome!

I was trying to add a default value to a field in my schema which is supposedly supported in the [graphql spec](http://spec.graphql.org/June2018/#DefaultValue) but I get a syntax error on the = when i run graph codegen.

#### Steps to reproduce:
1. in schema/graphql have a an entity like
```
type Entity @entity {
  myField: String = 'default'
}
```
2. run `graph build`
 
#### Error message: 
```
✖ Failed to load subgraph from subgraph.yaml: Invalid GraphQL schema: Syntax Error: Expected Name, found =

GraphQL request:8:21
7 | 	data: Bytes
8 | 	completed: Boolean = false
  |                     ^
9 | 	jobs: [NodeJobs!] @derivedFrom(field: "job")
Error: Invalid GraphQL schema: Syntax Error: Expected Name, found =

GraphQL request:8:21
7 | 	data: Bytes
8 | 	completed: Boolean = false
  |                     ^
9 | 	jobs: [NodeJobs!] @derivedFrom(field: "job")
    at parseSchema (/Users/kiba/code/lmfao/chainLink-oracle-subgraph/node_modules/@graphprotocol/graph-cli/src/validation/schema.js:65:11)
    at Object.validateSchema (/Users/kiba/code/lmfao/chainLink-oracle-subgraph/node_modules/@graphprotocol/graph-cli/src/validation/schema.js:943:16)
    at Function.validateSchema (/Users/kiba/code/lmfao/chainLink-oracle-subgraph/node_modules/@graphprotocol/graph-cli/src/subgraph.js:59:29)
    at Function.load (/Users/kiba/code/lmfao/chainLink-oracle-subgraph/node_modules/@graphprotocol/graph-cli/src/subgraph.js:438:14)
    at withSpinner (/Users/kiba/code/lmfao/chainLink-oracle-subgraph/node_modules/@graphprotocol/graph-cli/src/compiler.js:84:27)
    at withSpinner (/Users/kiba/code/lmfao/chainLink-oracle-subgraph/node_modules/@graphprotocol/graph-cli/src/command-helpers/spinner.js:29:24)
    at Compiler.loadSubgraph (/Users/kiba/code/lmfao/chainLink-oracle-subgraph/node_modules/@graphprotocol/graph-cli/src/compiler.js:79:20)
    at Compiler.compile (/Users/kiba/code/lmfao/chainLink-oracle-subgraph/node_modules/@graphprotocol/graph-cli/src/compiler.js:49:33)
    at process.runNextTicks [as _tickCallback] (internal/process/next_tick.js:47:5)
    at Function.Module.runMain (internal/modules/cjs/loader.js:804:11)
error Command failed with exit code 1.
```

#### Expected Behaviour
Adding a default value according to the GraphQL spec should compile correctly

**Comment by leoyvens** [comment]
Hi @kibagateaux, default values in graphql are for variables, arguments and input objects, not entity fields.
